# Fallback in case of local copy or not installed with setuptools
__version__ = "999"

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:  # pragma: no cover
    pass

__all__ = ["__version__"]
